{{- $name := include "poc-serverinfo-api.fullname" . -}}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ $name }}-vs"
spec:
  hosts:
    - caasnp1.internal.bupa.com.au
  gateways:
    - default/istio-internal-ingressgateway
  http:
    - match:
      - uri:
          prefix: /poc-serverinfo-{{ .Values.environment }}
      rewrite:
        uri: " "
      route:
      - destination:
          host: {{ $name }}-svc
          port:
            number: 80