{{- $name := include "serverinfo-api.fullname" . -}}

apiVersion: v1
kind: Service
metadata:
  name: "{{ $name }}-svc"
  labels:
    app.kubernetes.io/name: {{ template "serverinfo-api.name" . }}
    chart: {{ template "serverinfo-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ $name }}
    release: {{ .Release.Name }}
